ktor:
  deployment:
    port: 8081

  application:
    modules:
      - com.featup.ApplicationKt.module

database:
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/featsup"
  user: "postgres"
  password: "nesantari"

jwt:
  secret: "Z7f9Lq28hGmP3x!92BvKq#sDfT1rX8"
  issuer: "featup"
  audience: "featup_audience"
  realm: "featup-realm"
  expiresInMinutes: 60
